//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceLate
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WSYouAreLate")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/WSYouAreLate.DTO")]
    public partial class UserDTO : object
    {
        
        private string classeField;
        
        private string firstnameField;
        
        private string identifiantField;
        
        private int iduserField;
        
        private string lastnameField;
        
        private string passwordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string classe
        {
            get
            {
                return this.classeField;
            }
            set
            {
                this.classeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identifiant
        {
            get
            {
                return this.identifiantField;
            }
            set
            {
                this.identifiantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iduser
        {
            get
            {
                return this.iduserField;
            }
            set
            {
                this.iduserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="users", Namespace="http://schemas.datacontract.org/2004/07/WSYouAreLate.Entities")]
    public partial class users : object
    {
        
        private string classeField;
        
        private string firstnameField;
        
        private string identifiantField;
        
        private int idusersField;
        
        private string lastnameField;
        
        private ServiceReferenceLate.lateticket[] lateticketField;
        
        private string passwordField;
        
        private ServiceReferenceLate.users_late[] users_lateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string classe
        {
            get
            {
                return this.classeField;
            }
            set
            {
                this.classeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identifiant
        {
            get
            {
                return this.identifiantField;
            }
            set
            {
                this.identifiantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idusers
        {
            get
            {
                return this.idusersField;
            }
            set
            {
                this.idusersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceLate.lateticket[] lateticket
        {
            get
            {
                return this.lateticketField;
            }
            set
            {
                this.lateticketField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceLate.users_late[] users_late
        {
            get
            {
                return this.users_lateField;
            }
            set
            {
                this.users_lateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="lateticket", Namespace="http://schemas.datacontract.org/2004/07/WSYouAreLate.Entities")]
    public partial class lateticket : object
    {
        
        private string SubjectField;
        
        private System.DateTime datetimeField;
        
        private int idField;
        
        private int idUserField;
        
        private string imageField;
        
        private ServiceReferenceLate.users usersField;
        
        private ServiceReferenceLate.users_late[] users_lateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime datetime
        {
            get
            {
                return this.datetimeField;
            }
            set
            {
                this.datetimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUser
        {
            get
            {
                return this.idUserField;
            }
            set
            {
                this.idUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceLate.users users
        {
            get
            {
                return this.usersField;
            }
            set
            {
                this.usersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceLate.users_late[] users_late
        {
            get
            {
                return this.users_lateField;
            }
            set
            {
                this.users_lateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="users_late", Namespace="http://schemas.datacontract.org/2004/07/WSYouAreLate.Entities")]
    public partial class users_late : object
    {
        
        private int IdlateField;
        
        private int IdusersField;
        
        private System.Nullable<sbyte> VoteField;
        
        private ServiceReferenceLate.lateticket lateticketField;
        
        private ServiceReferenceLate.users usersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idlate
        {
            get
            {
                return this.IdlateField;
            }
            set
            {
                this.IdlateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idusers
        {
            get
            {
                return this.IdusersField;
            }
            set
            {
                this.IdusersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<sbyte> Vote
        {
            get
            {
                return this.VoteField;
            }
            set
            {
                this.VoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceLate.lateticket lateticket
        {
            get
            {
                return this.lateticketField;
            }
            set
            {
                this.lateticketField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceLate.users users
        {
            get
            {
                return this.usersField;
            }
            set
            {
                this.usersField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLate.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ServiceReferenceLate.CompositeType GetDataUsingDataContract(ServiceReferenceLate.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.CompositeType> GetDataUsingDataContractAsync(ServiceReferenceLate.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        ServiceReferenceLate.UserDTO[] GetUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.UserDTO[]> GetUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AuthentificateUser", ReplyAction="http://tempuri.org/IService1/AuthentificateUserResponse")]
        ServiceReferenceLate.users AuthentificateUser(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AuthentificateUser", ReplyAction="http://tempuri.org/IService1/AuthentificateUserResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.users> AuthentificateUserAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateUser", ReplyAction="http://tempuri.org/IService1/CreateUserResponse")]
        ServiceReferenceLate.UserDTO CreateUser(ServiceReferenceLate.users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateUser", ReplyAction="http://tempuri.org/IService1/CreateUserResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.UserDTO> CreateUserAsync(ServiceReferenceLate.users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateCommentary", ReplyAction="http://tempuri.org/IService1/CreateCommentaryResponse")]
        void CreateCommentary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateCommentary", ReplyAction="http://tempuri.org/IService1/CreateCommentaryResponse")]
        System.Threading.Tasks.Task CreateCommentaryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCommentary", ReplyAction="http://tempuri.org/IService1/DeleteCommentaryResponse")]
        void DeleteCommentary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCommentary", ReplyAction="http://tempuri.org/IService1/DeleteCommentaryResponse")]
        System.Threading.Tasks.Task DeleteCommentaryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLateNotification", ReplyAction="http://tempuri.org/IService1/GetLateNotificationResponse")]
        void GetLateNotification();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLateNotification", ReplyAction="http://tempuri.org/IService1/GetLateNotificationResponse")]
        System.Threading.Tasks.Task GetLateNotificationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLateNotification", ReplyAction="http://tempuri.org/IService1/DeleteLateNotificationResponse")]
        void DeleteLateNotification();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLateNotification", ReplyAction="http://tempuri.org/IService1/DeleteLateNotificationResponse")]
        System.Threading.Tasks.Task DeleteLateNotificationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateLateNotification", ReplyAction="http://tempuri.org/IService1/UpdateLateNotificationResponse")]
        void UpdateLateNotification();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateLateNotification", ReplyAction="http://tempuri.org/IService1/UpdateLateNotificationResponse")]
        System.Threading.Tasks.Task UpdateLateNotificationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateLateNotification", ReplyAction="http://tempuri.org/IService1/CreateLateNotificationResponse")]
        void CreateLateNotification();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateLateNotification", ReplyAction="http://tempuri.org/IService1/CreateLateNotificationResponse")]
        System.Threading.Tasks.Task CreateLateNotificationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LikeLateNotification", ReplyAction="http://tempuri.org/IService1/LikeLateNotificationResponse")]
        void LikeLateNotification();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LikeLateNotification", ReplyAction="http://tempuri.org/IService1/LikeLateNotificationResponse")]
        System.Threading.Tasks.Task LikeLateNotificationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DisLikeLateNotification", ReplyAction="http://tempuri.org/IService1/DisLikeLateNotificationResponse")]
        void DisLikeLateNotification();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DisLikeLateNotification", ReplyAction="http://tempuri.org/IService1/DisLikeLateNotificationResponse")]
        System.Threading.Tasks.Task DisLikeLateNotificationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IService1Channel : ServiceReferenceLate.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReferenceLate.IService1>, ServiceReferenceLate.IService1
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetData(int value)
        {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public ServiceReferenceLate.CompositeType GetDataUsingDataContract(ServiceReferenceLate.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.CompositeType> GetDataUsingDataContractAsync(ServiceReferenceLate.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ServiceReferenceLate.UserDTO[] GetUser()
        {
            return base.Channel.GetUser();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.UserDTO[]> GetUserAsync()
        {
            return base.Channel.GetUserAsync();
        }
        
        public ServiceReferenceLate.users AuthentificateUser(string login, string password)
        {
            return base.Channel.AuthentificateUser(login, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.users> AuthentificateUserAsync(string login, string password)
        {
            return base.Channel.AuthentificateUserAsync(login, password);
        }
        
        public ServiceReferenceLate.UserDTO CreateUser(ServiceReferenceLate.users user)
        {
            return base.Channel.CreateUser(user);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.UserDTO> CreateUserAsync(ServiceReferenceLate.users user)
        {
            return base.Channel.CreateUserAsync(user);
        }
        
        public void CreateCommentary()
        {
            base.Channel.CreateCommentary();
        }
        
        public System.Threading.Tasks.Task CreateCommentaryAsync()
        {
            return base.Channel.CreateCommentaryAsync();
        }
        
        public void DeleteCommentary()
        {
            base.Channel.DeleteCommentary();
        }
        
        public System.Threading.Tasks.Task DeleteCommentaryAsync()
        {
            return base.Channel.DeleteCommentaryAsync();
        }
        
        public void GetLateNotification()
        {
            base.Channel.GetLateNotification();
        }
        
        public System.Threading.Tasks.Task GetLateNotificationAsync()
        {
            return base.Channel.GetLateNotificationAsync();
        }
        
        public void DeleteLateNotification()
        {
            base.Channel.DeleteLateNotification();
        }
        
        public System.Threading.Tasks.Task DeleteLateNotificationAsync()
        {
            return base.Channel.DeleteLateNotificationAsync();
        }
        
        public void UpdateLateNotification()
        {
            base.Channel.UpdateLateNotification();
        }
        
        public System.Threading.Tasks.Task UpdateLateNotificationAsync()
        {
            return base.Channel.UpdateLateNotificationAsync();
        }
        
        public void CreateLateNotification()
        {
            base.Channel.CreateLateNotification();
        }
        
        public System.Threading.Tasks.Task CreateLateNotificationAsync()
        {
            return base.Channel.CreateLateNotificationAsync();
        }
        
        public void LikeLateNotification()
        {
            base.Channel.LikeLateNotification();
        }
        
        public System.Threading.Tasks.Task LikeLateNotificationAsync()
        {
            return base.Channel.LikeLateNotificationAsync();
        }
        
        public void DisLikeLateNotification()
        {
            base.Channel.DisLikeLateNotification();
        }
        
        public System.Threading.Tasks.Task DisLikeLateNotificationAsync()
        {
            return base.Channel.DisLikeLateNotificationAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:51188/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
