//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceLate
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WSYouAreLate")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/WSYouAreLate.DTO")]
    public partial class UserDTO : object
    {
        
        private string classeField;
        
        private string firstnameField;
        
        private int idField;
        
        private string identifiantField;
        
        private string lastnameField;
        
        private string passwordField;
        
        private ServiceReferenceLate.LateTicketDTO[] ticketsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string classe
        {
            get
            {
                return this.classeField;
            }
            set
            {
                this.classeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string identifiant
        {
            get
            {
                return this.identifiantField;
            }
            set
            {
                this.identifiantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceLate.LateTicketDTO[] tickets
        {
            get
            {
                return this.ticketsField;
            }
            set
            {
                this.ticketsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LateTicketDTO", Namespace="http://schemas.datacontract.org/2004/07/WSYouAreLate.DTO")]
    public partial class LateTicketDTO : object
    {
        
        private string SubjectField;
        
        private System.DateTime datetimeField;
        
        private int idField;
        
        private int idUserField;
        
        private string imageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime datetime
        {
            get
            {
                return this.datetimeField;
            }
            set
            {
                this.datetimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUser
        {
            get
            {
                return this.idUserField;
            }
            set
            {
                this.idUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLateDTO", Namespace="http://schemas.datacontract.org/2004/07/WSYouAreLate.DTO")]
    public partial class UserLateDTO : object
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLate.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ServiceReferenceLate.CompositeType GetDataUsingDataContract(ServiceReferenceLate.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.CompositeType> GetDataUsingDataContractAsync(ServiceReferenceLate.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        ServiceReferenceLate.UserDTO[] GetUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUser", ReplyAction="http://tempuri.org/IService1/GetUserResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.UserDTO[]> GetUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AuthentificateUser", ReplyAction="http://tempuri.org/IService1/AuthentificateUserResponse")]
        ServiceReferenceLate.UserDTO AuthentificateUser(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AuthentificateUser", ReplyAction="http://tempuri.org/IService1/AuthentificateUserResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.UserDTO> AuthentificateUserAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateUser", ReplyAction="http://tempuri.org/IService1/CreateUserResponse")]
        ServiceReferenceLate.UserDTO CreateUser(ServiceReferenceLate.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateUser", ReplyAction="http://tempuri.org/IService1/CreateUserResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.UserDTO> CreateUserAsync(ServiceReferenceLate.UserDTO user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLateTickets", ReplyAction="http://tempuri.org/IService1/GetLateTicketsResponse")]
        ServiceReferenceLate.LateTicketDTO[] GetLateTickets();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLateTickets", ReplyAction="http://tempuri.org/IService1/GetLateTicketsResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.LateTicketDTO[]> GetLateTicketsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLateTicket", ReplyAction="http://tempuri.org/IService1/DeleteLateTicketResponse")]
        ServiceReferenceLate.LateTicketDTO DeleteLateTicket(ServiceReferenceLate.LateTicketDTO lateTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLateTicket", ReplyAction="http://tempuri.org/IService1/DeleteLateTicketResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.LateTicketDTO> DeleteLateTicketAsync(ServiceReferenceLate.LateTicketDTO lateTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateLateTicket", ReplyAction="http://tempuri.org/IService1/UpdateLateTicketResponse")]
        ServiceReferenceLate.LateTicketDTO UpdateLateTicket(ServiceReferenceLate.LateTicketDTO lateTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateLateTicket", ReplyAction="http://tempuri.org/IService1/UpdateLateTicketResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.LateTicketDTO> UpdateLateTicketAsync(ServiceReferenceLate.LateTicketDTO lateTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateLateTicket", ReplyAction="http://tempuri.org/IService1/CreateLateTicketResponse")]
        ServiceReferenceLate.LateTicketDTO CreateLateTicket(ServiceReferenceLate.LateTicketDTO lateTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateLateTicket", ReplyAction="http://tempuri.org/IService1/CreateLateTicketResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.LateTicketDTO> CreateLateTicketAsync(ServiceReferenceLate.LateTicketDTO lateTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LikeLateTicket", ReplyAction="http://tempuri.org/IService1/LikeLateTicketResponse")]
        void LikeLateTicket(ServiceReferenceLate.UserLateDTO usersLate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LikeLateTicket", ReplyAction="http://tempuri.org/IService1/LikeLateTicketResponse")]
        System.Threading.Tasks.Task LikeLateTicketAsync(ServiceReferenceLate.UserLateDTO usersLate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DisLikeLateTicket", ReplyAction="http://tempuri.org/IService1/DisLikeLateTicketResponse")]
        void DisLikeLateTicket(ServiceReferenceLate.UserLateDTO usersLate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DisLikeLateTicket", ReplyAction="http://tempuri.org/IService1/DisLikeLateTicketResponse")]
        System.Threading.Tasks.Task DisLikeLateTicketAsync(ServiceReferenceLate.UserLateDTO usersLate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateCommentary", ReplyAction="http://tempuri.org/IService1/CreateCommentaryResponse")]
        void CreateCommentary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateCommentary", ReplyAction="http://tempuri.org/IService1/CreateCommentaryResponse")]
        System.Threading.Tasks.Task CreateCommentaryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCommentary", ReplyAction="http://tempuri.org/IService1/DeleteCommentaryResponse")]
        void DeleteCommentary();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCommentary", ReplyAction="http://tempuri.org/IService1/DeleteCommentaryResponse")]
        System.Threading.Tasks.Task DeleteCommentaryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLinks", ReplyAction="http://tempuri.org/IService1/GetLinksResponse")]
        ServiceReferenceLate.UserLateDTO[] GetLinks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLinks", ReplyAction="http://tempuri.org/IService1/GetLinksResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.UserLateDTO[]> GetLinksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddLinkUserToVote", ReplyAction="http://tempuri.org/IService1/AddLinkUserToVoteResponse")]
        ServiceReferenceLate.UserLateDTO AddLinkUserToVote(ServiceReferenceLate.UserLateDTO usersLate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddLinkUserToVote", ReplyAction="http://tempuri.org/IService1/AddLinkUserToVoteResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.UserLateDTO> AddLinkUserToVoteAsync(ServiceReferenceLate.UserLateDTO usersLate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLinkUserToVote", ReplyAction="http://tempuri.org/IService1/DeleteLinkUserToVoteResponse")]
        ServiceReferenceLate.UserLateDTO DeleteLinkUserToVote(ServiceReferenceLate.UserLateDTO usersLate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteLinkUserToVote", ReplyAction="http://tempuri.org/IService1/DeleteLinkUserToVoteResponse")]
        System.Threading.Tasks.Task<ServiceReferenceLate.UserLateDTO> DeleteLinkUserToVoteAsync(ServiceReferenceLate.UserLateDTO usersLate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IService1Channel : ServiceReferenceLate.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReferenceLate.IService1>, ServiceReferenceLate.IService1
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetData(int value)
        {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public ServiceReferenceLate.CompositeType GetDataUsingDataContract(ServiceReferenceLate.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.CompositeType> GetDataUsingDataContractAsync(ServiceReferenceLate.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ServiceReferenceLate.UserDTO[] GetUser()
        {
            return base.Channel.GetUser();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.UserDTO[]> GetUserAsync()
        {
            return base.Channel.GetUserAsync();
        }
        
        public ServiceReferenceLate.UserDTO AuthentificateUser(string login, string password)
        {
            return base.Channel.AuthentificateUser(login, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.UserDTO> AuthentificateUserAsync(string login, string password)
        {
            return base.Channel.AuthentificateUserAsync(login, password);
        }
        
        public ServiceReferenceLate.UserDTO CreateUser(ServiceReferenceLate.UserDTO user)
        {
            return base.Channel.CreateUser(user);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.UserDTO> CreateUserAsync(ServiceReferenceLate.UserDTO user)
        {
            return base.Channel.CreateUserAsync(user);
        }
        
        public ServiceReferenceLate.LateTicketDTO[] GetLateTickets()
        {
            return base.Channel.GetLateTickets();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.LateTicketDTO[]> GetLateTicketsAsync()
        {
            return base.Channel.GetLateTicketsAsync();
        }
        
        public ServiceReferenceLate.LateTicketDTO DeleteLateTicket(ServiceReferenceLate.LateTicketDTO lateTicket)
        {
            return base.Channel.DeleteLateTicket(lateTicket);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.LateTicketDTO> DeleteLateTicketAsync(ServiceReferenceLate.LateTicketDTO lateTicket)
        {
            return base.Channel.DeleteLateTicketAsync(lateTicket);
        }
        
        public ServiceReferenceLate.LateTicketDTO UpdateLateTicket(ServiceReferenceLate.LateTicketDTO lateTicket)
        {
            return base.Channel.UpdateLateTicket(lateTicket);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.LateTicketDTO> UpdateLateTicketAsync(ServiceReferenceLate.LateTicketDTO lateTicket)
        {
            return base.Channel.UpdateLateTicketAsync(lateTicket);
        }
        
        public ServiceReferenceLate.LateTicketDTO CreateLateTicket(ServiceReferenceLate.LateTicketDTO lateTicket)
        {
            return base.Channel.CreateLateTicket(lateTicket);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.LateTicketDTO> CreateLateTicketAsync(ServiceReferenceLate.LateTicketDTO lateTicket)
        {
            return base.Channel.CreateLateTicketAsync(lateTicket);
        }
        
        public void LikeLateTicket(ServiceReferenceLate.UserLateDTO usersLate)
        {
            base.Channel.LikeLateTicket(usersLate);
        }
        
        public System.Threading.Tasks.Task LikeLateTicketAsync(ServiceReferenceLate.UserLateDTO usersLate)
        {
            return base.Channel.LikeLateTicketAsync(usersLate);
        }
        
        public void DisLikeLateTicket(ServiceReferenceLate.UserLateDTO usersLate)
        {
            base.Channel.DisLikeLateTicket(usersLate);
        }
        
        public System.Threading.Tasks.Task DisLikeLateTicketAsync(ServiceReferenceLate.UserLateDTO usersLate)
        {
            return base.Channel.DisLikeLateTicketAsync(usersLate);
        }
        
        public void CreateCommentary()
        {
            base.Channel.CreateCommentary();
        }
        
        public System.Threading.Tasks.Task CreateCommentaryAsync()
        {
            return base.Channel.CreateCommentaryAsync();
        }
        
        public void DeleteCommentary()
        {
            base.Channel.DeleteCommentary();
        }
        
        public System.Threading.Tasks.Task DeleteCommentaryAsync()
        {
            return base.Channel.DeleteCommentaryAsync();
        }
        
        public ServiceReferenceLate.UserLateDTO[] GetLinks()
        {
            return base.Channel.GetLinks();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.UserLateDTO[]> GetLinksAsync()
        {
            return base.Channel.GetLinksAsync();
        }
        
        public ServiceReferenceLate.UserLateDTO AddLinkUserToVote(ServiceReferenceLate.UserLateDTO usersLate)
        {
            return base.Channel.AddLinkUserToVote(usersLate);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.UserLateDTO> AddLinkUserToVoteAsync(ServiceReferenceLate.UserLateDTO usersLate)
        {
            return base.Channel.AddLinkUserToVoteAsync(usersLate);
        }
        
        public ServiceReferenceLate.UserLateDTO DeleteLinkUserToVote(ServiceReferenceLate.UserLateDTO usersLate)
        {
            return base.Channel.DeleteLinkUserToVote(usersLate);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceLate.UserLateDTO> DeleteLinkUserToVoteAsync(ServiceReferenceLate.UserLateDTO usersLate)
        {
            return base.Channel.DeleteLinkUserToVoteAsync(usersLate);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50000/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
